"""Compile component sources without rewriting them or reordering the cascade."""
from pathlib import Path
import argparse
import json
import re

ROOT = Path(__file__).resolve().parent.parent
HEADER = '/* Generated by tools/build-css.py. Edit css/modules, then rebuild. */\n'
MARKER = re.compile(r'^/\* @section ([a-zA-Z0-9_-]+) \*/\s*$', re.M)


def compile_css(root=ROOT):
    manifest = json.loads((root / 'css/manifest.json').read_text())
    if manifest.get('version') != 2:
        raise ValueError('Unsupported CSS manifest version')
    sections = {}
    files = manifest['files']
    if len(files) != len(set(files)):
        raise ValueError('Duplicate CSS source file')
    for file in files:
        path = (root / file).resolve()
        if not path.is_relative_to((root / 'css/modules').resolve()):
            raise ValueError('CSS sources must be inside css/modules')
        source = path.read_text()
        markers = list(MARKER.finditer(source))
        if not markers:
            raise ValueError(f'No sections in {file}')
        prefix = re.sub(r'/\*.*?\*/', '', source[:markers[0].start()], flags=re.S)
        if prefix.strip():
            raise ValueError(f'Rules outside sections in {file}')
        for i, match in enumerate(markers):
            key = match.group(1)
            if key in sections:
                raise ValueError(f'Duplicate CSS section: {key}')
            end = markers[i + 1].start() if i + 1 < len(markers) else len(source)
            sections[key] = (file, source[match.end():end].strip())
    actual = {str(path.relative_to(root)) for path in (root / 'css/modules').glob('*.css')}
    if actual != set(files):
        raise ValueError('CSS files missing from manifest or missing on disk')
    output = HEADER
    used = set()
    for entry in manifest['sections']:
        key, file = entry['id'], entry['file']
        if key in used or key not in sections:
            raise ValueError(f'Duplicate or missing ordered section: {key}')
        if sections[key][0] != file:
            raise ValueError(f'Wrong owner for section: {key}')
        used.add(key)
        body = re.sub(r'(url\(\s*["\']?)\.\./\.\./', r'\1../', sections[key][1])
        output += f'\n/* {file} @section {key} */\n{body}\n'
    if used != set(sections):
        raise ValueError('Unordered CSS sections')
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    manifest = json.loads((ROOT / 'css/manifest.json').read_text())
    compiled = compile_css()
    target = ROOT / manifest['runtime']
    if target.resolve() != (ROOT / 'css/game.css').resolve():
        raise ValueError('Runtime must be css/game.css')
    if args.check:
        if target.read_text() != compiled:
            raise ValueError('CSS build is stale: run python3 tools/build-css.py')
        print('OK: CSS runtime matches component sources and cascade order.')
    else:
        target.write_text(compiled)
        print('Built css/game.css; source files unchanged.')


if __name__ == '__main__':
    main()
