'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {createRuntime}=require('./helpers/season-runtime'),root=path.resolve(__dirname,'..'),window={};
vm.runInNewContext(fs.readFileSync(path.join(root,'js/auction-events.js'),'utf8'),{window});
const events=window.FantaAuctionEvents;
assert.equal(events.settings.arcadeChance,.05);assert.equal(events.rollArcade(['sealed'],()=>.05),null);
for(let i=0;i<2;i++)assert.equal(events.rollArcade(['sealed'],()=>.049),'sealed');
assert.equal(events.sealedWinner([{managerId:'a',amount:10},{managerId:'b',amount:10}],['b','a']).managerId,'b');
const api=createRuntime('arcade-regression'),elements=new Map();
function element(id){if(!elements.has(id))elements.set(id,{textContent:'',innerHTML:'',value:'1',hidden:false,style:{setProperty(){}},classList:{add(){},remove(){},toggle(){},contains(){return false;}},setAttribute(){},closest(){return null;},parentElement:null,querySelector(){return null;},focus(){}});return elements.get(id);}
api.noticeTestElements(new Proxy({},{get:(_,id)=>element(id)}));
let state=api.arcadeInitialize(),player=api.players().find(p=>p.role==='A'),a=api.arcadePrepare(player,1);
assert.equal(a.arcade.type,'mystery');
const hidden=api.players().find(p=>p.id===a.playerId),cpu=state.managers[1],first=api.arcadeLimit(cpu,hidden);
const sameClub=api.players().find(p=>p.club===hidden.club&&p.role===hidden.role&&p.id!==hidden.id);
if(sameClub){a.playerId=sameClub.id;assert.equal(api.arcadeLimit(cpu,sameClub),first);a.playerId=hidden.id;}
state.auctionPowers.selected=['observer'];api.arcadeRender();assert.equal(element('auctionName').textContent,'PACCO SORPRESA');assert.equal(element('auctionOvr').textContent,'OVR ???');assert(!element('auctionAvatar').innerHTML.includes(hidden.name));assert.notEqual(element('auctionPotentialLabel').textContent,'—');assert.match(element('auctionStarterPct').textContent,/%$/);
state.auctionPowers.selected=[];api.arcadeRender();assert.equal(element('auctionPotentialLabel').textContent,'—');assert.equal(api.storageSnapshot().auction.playerId,a.playerId);
state=api.arcadeInitialize();a=api.arcadePrepare(player,0);assert.equal(a.arcade.type,'sealed');
const saved=JSON.stringify(a.arcade.offers);api.arcadeShow();api.arcadeShow();assert.equal(JSON.stringify(a.arcade.offers),saved);
element('arcadeSealedAmount').value='9999';api.arcadeAction('submit');assert(!a.arcade.resolved);assert(element('arcadeSealedError').textContent);
element('arcadeSealedAmount').value='12';api.arcadeAction('submit');assert(a.arcade.resolved);assert.equal(a.arcade.offers.filter(o=>o.managerId==='user').length,1);api.arcadeAction('submit');assert.equal(a.arcade.offers.filter(o=>o.managerId==='user').length,1);
const winner=a.highBidderId,price=a.price;api.arcadeResolve();assert.equal(a.price,price);assert.equal(a.highBidderId,winner);assert.equal(api.storageSnapshot().auction.arcade.resolved,true);
state=api.arcadeInitialize();a=api.arcadePrepare(player,2);assert.equal(a.arcade.type,'bundle');
state.auctionPowers.selected=['observer'];api.arcadeRender();const bundleMarkup=element('auctionBundlePlayers').innerHTML;assert(bundleMarkup.includes(player.name));assert(bundleMarkup.includes(api.players().find(p=>p.id===a.arcade.secondPlayerId).name));assert.equal((bundleMarkup.match(/PROB. TITOLARE/g)||[]).length,2);assert.equal((bundleMarkup.match(/POTENZIALE STAGIONE/g)||[]).length,2);state.auctionPowers.selected=[];api.arcadeRender();assert(!element('auctionBundlePlayers').innerHTML.includes('PROB. TITOLARE'));
const second=api.players().find(p=>p.id===a.arcade.secondPlayerId),engine=api.arcadeEngine(),limits={P:3,D:8,C:8,A:6},me=state.managers[0],budget=me.budget;
assert.equal(engine.awardBundle(state,[player,second],'user',30,{roleLimits:limits,totalSlots:25}).ok,true);assert.equal(me.budget,budget-30);assert.equal(me.roster.length,2);assert.equal(me.roster.reduce((s,p)=>s+p.price,0),30);assert.equal(state.stats.purchases,2);assert(!state.availableIds.includes(player.id));assert(!state.availableIds.includes(second.id));
const badState={managers:[{id:'user',budget:30,roster:[]}],availableIds:[player.id],stats:{purchases:0,totalSpent:0}},before=JSON.stringify(badState);
assert.equal(engine.awardBundle(badState,[player,second],'user',10,{roleLimits:limits,totalSlots:25}).ok,false);assert.equal(JSON.stringify(badState),before);
assert.equal(engine.maxBundleBid({budget:30,roster:Array.from({length:5},(_,i)=>({id:i,role:'A'}))},[player,second],limits),0);
console.log('Arcade: frequency, repeats, observer, hidden CPU information, sealed persistence and atomic bundles passed.');
