'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..'),manifest=JSON.parse(fs.readFileSync(path.join(root,'css/manifest.json')));
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert(html.includes('href="'+manifest.runtime+'"'));
assert.equal(manifest.files.at(-1),'css/modules/12-responsive-qa.css');
let expected='/* Generated by tools/consolidate-css.py. Edit css/modules, then rebuild. */\n';
for(const file of manifest.files){const source=fs.readFileSync(path.join(root,file),'utf8').replace(/(url\(\s*["']?)\.\.\/\.\.\//g,'$1../');expected+='\n/* '+file+' */\n'+source+'\n';}
const css=fs.readFileSync(path.join(root,manifest.runtime),'utf8');assert.equal(css,expected,'runtime CSS must exactly reproduce source order and relative paths');
assert(!/@import\b/.test(css),'one runtime stylesheet, no import waterfall');
for(const url of css.matchAll(/url\(\s*["']?([^\s"')]+)["']?\s*\)/g)){
 if(/^(data:|https?:|#)/.test(url[1]))continue;
 assert(fs.existsSync(path.resolve(root,'css',url[1].split(/[?#]/)[0])),'asset: '+url[1]);
}
console.log('OK: build CSS aggiornato, ordine responsive invariato, risorse relative valide e nessun @import a runtime.');
