'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const window={};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../js/domains/datacenter-views.js'),'utf8'),{window});
let handlers={},wired=0;
const body={innerHTML:'',querySelector:()=>null,querySelectorAll(selector){const attr=selector.slice(1,-1),re=new RegExp(attr+'="([^"]*)"','g');return Array.from(this.innerHTML.matchAll(re),match=>({dataset:{[attr==='data-dct-sort'?'dctSort':'dctRole']:match[1]},addEventListener(event,fn){handlers[attr+':'+match[1]]=fn;}}));}};
const roster=[{id:'a',name:'Alfa',role:'A',club:'Uno',price:5,ovr:70},{id:'b',name:'Beta',role:'P',club:'Due',price:20,ovr:80}];
const ctx={roster,dataPro:false,scoutPlus:false};
const runtime={$:()=>body,playerSeasonStat:id=>({appearances:3,goals:id==='a'?4:0,voteCount:2,voteSum:14,fantasySum:id==='a'?20:12}),emptyPlayerSeasonStat:()=>({}),currentPlayerOvr:p=>p.ovr,estimatedStarterProbability:()=>75,escapeHtml:x=>String(x).replaceAll('"','&quot;'),playerAvatarMarkup:()=>'<img alt="" src="face">',wireSeasonPlayerButtons:()=>wired++};
const api=window.FantaDomains['datacenter-views'].create(runtime),render=()=>api.renderDataCenterPlayersPanel(ctx);
const ids=()=>Array.from(body.innerHTML.matchAll(/data-season-player="([^"]+)"/g),m=>m[1]);
render();assert.deepEqual(ids(),['b','a']);assert(body.innerHTML.includes('manca FantaData Pro'));assert(body.innerHTML.includes('manca Scout Plus'));assert(!body.innerHTML.includes('10.00'));handlers['data-dct-sort:goals']();assert.deepEqual(ids(),['a','b']);handlers['data-dct-sort:goals']();assert.deepEqual(ids(),['b','a']);handlers['data-dct-role:A']();assert.deepEqual(ids(),['a']);handlers['data-dct-role:']();ctx.dataPro=true;ctx.scoutPlus=true;render();assert(body.innerHTML.includes('10.00'));assert(body.innerHTML.includes('75%'));handlers['data-dct-sort:fm']();assert.deepEqual(ids(),['a','b']);assert(wired>=7);assert.deepEqual(roster.map(p=>p.id),['a','b']);
console.log('OK: rosa personale, ordinamento reversibile, filtro ruoli, blocchi premium, dati e schede giocatore.');
