'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {create,auctionSnapshot}=require('../js/presentation-state');
const rules={totalSlots:25,roleLimits:{P:3,D:8,C:8,A:6}},state={managers:[{budget:500,roster:[{role:'P'},{role:'A'}]}],auction:null};
const before=JSON.stringify(state),snapshot=auctionSnapshot(state,rules);
assert.equal(JSON.stringify(state),before);assert(Object.isFrozen(snapshot)&&Object.isFrozen(snapshot.roles)&&snapshot.roles.every(Object.isFrozen));assert.equal(snapshot.roles.find(r=>r.role==='A').count,1);assert.equal(snapshot.phase,'nomination');
const store=create(),notifications=[],stop=store.subscribeAuction(s=>notifications.push(s));assert.equal(notifications[0],null);
store.publishAuction(state,rules);const first=store.getAuction();store.publishAuction(state,rules);assert.equal(notifications.length,2);assert.equal(store.getAuction(),first);
state.auction={playerId:'same-player'};store.publishAuction(state,{...rules,userCanAct:true});assert.equal(store.getAuction().canBid,true);
state.managers[0].budget=470;store.publishAuction(state,rules);assert.equal(store.getAuction().canBid,true);assert.equal(store.getAuction().budget,470);assert.equal(first.budget,500);
const other={managers:[{budget:99,roster:[]}],auction:{playerId:'same-player'}};store.publishAuction(other,rules);assert.equal(store.getAuction().canBid,false,'A new auction must not inherit action availability');assert.equal(store.getAuction().filledSlots,0);
other.completed=true;store.publishAuction(other,{...rules,userCanAct:true});assert.equal(store.getAuction().phase,'completed');assert.equal(store.getAuction().canBid,false);
store.publishAuction(null,rules);assert.equal(store.getAuction(),null);const count=notifications.length;stop();store.publishAuction(state,rules);assert.equal(notifications.length,count);
const root=path.join(__dirname,'..'),model=fs.readFileSync(path.join(root,'js/presentation-state.js'),'utf8'),mobile=fs.readFileSync(path.join(root,'js/mobile-auction-app.js'),'utf8'),ui=fs.readFileSync(path.join(root,'js/mobile-ui.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert(!/\b(document|localStorage|indexedDB|MutationObserver)\b/.test(model),'Snapshot must not depend on DOM or persistence');
assert(!/MutationObserver|myBudget|mySlots|roleNeed['"]|liveAuction|userBidControls/.test(mobile),'Mobile data must not come from desktop text or visibility classes');
assert(!/closest\(['"]\.mobile-auction-fold|querySelector\(['"]\.auction-bottom-row/.test(mobile));
assert(!ui.includes('createElement(\'details\')'),'Fold structure is declared in HTML');
for(const anchor of ['auction-controls','lineup-sections','lineup-help','live-content','live-score','live-sections'])assert.equal(html.split('data-mobile-anchor="'+anchor+'"').length-1,1,anchor+' has one declared owner');
assert.equal(html.split('data-mobile-auction-region="league"').length-1,4);
for(const file of ['presentation-state','mobile-locations'])assert(html.indexOf('src="js/'+file+'.js"')<html.indexOf('src="app_v302.js"'));
console.log('OK: immutable presentation snapshots, state replacement, notification deduplication, unsubscription and declarative DOM contracts.');
